### ISSUE TITLE
setData() documentation is incorrect

### ISSUE THREAD

**Issue by miketahani** [cyrilcherian/Leaflet-Fullcanvas#3]
It states 

```
//add points to the layer...here slat denotes the latitude and slon denotes the longitude
layer.setData({"slat": -33.3042, "slon": 26.5328});
```

but setData() only takes arrays of points, not single points (and re-draws the layer). Should say "addData".

**Comment by miketahani** [comment]
Additionally, it is not possible to add live data to the map because setData initializes a new quadtree every time it is called.

**Comment by cyrilcherian** [comment]
Yep correct!
I have corrected the Readme file accordingly thanks!
